version: "3.6"

services:
  n2o-sandbox:
    image: "${DOCKER_REGISTRY}/n2o/n2o-sandbox:${TAG}"
    environment:
      - N2O_SANDBOX_URL=https://sandbox.n2oapp.net
    ports:
      - "${PORT}:8080"
    deploy:
      resources:
        limits:
          memory: 512M
      placement:
        constraints:
          - node.role == worker
