version: "3.6"

services:
  frontend:
    ports:
      - "8700:8080"
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/next/demo
  storybook:
    ports:
      - "8702:80"
  docusaurus:
    ports:
      - "8703:80"
