version: "3.6"

services:
  frontend:
    image: 538721144237.dkr.ecr.eu-west-1.amazonaws.com/n2o/demo
    deploy:
      resources:
        limits:
          memory: 700M
      placement:
        constraints:
          - node.labels.dc == hetzner
  docs:
    image: 538721144237.dkr.ecr.eu-west-1.amazonaws.com/n2o/docs
    deploy:
      resources:
        limits:
          memory: 700M
      placement:
        constraints:
          - node.labels.dc == hetzner
  storybook:
    image: 538721144237.dkr.ecr.eu-west-1.amazonaws.com/n2o/storybook
    deploy:
      resources:
        limits:
          memory: 256M
      placement:
        constraints:
          - node.labels.dc == hetzner