version: "3.6"

services:
  frontend:
    image: "${DOCKER_REGISTRY}/n2o/demo:${TAG}"
    build:
      context: demo/server
  storybook:
    image: "${DOCKER_REGISTRY}/n2o/storybook:${TAG}"
    build:
      context: frontend/n2o-framework
  docusaurus:
    image: "${DOCKER_REGISTRY}/n2o/docusaurus:${TAG}"
    build:
      context: frontend/docs
