version: "3.6"

services:
  frontend:
    ports:
      - "8220:8080"
    deploy:
      resources:
        limits:
          memory: 700M
      placement:
        constraints:
          - node.labels.dc == hetzner
  docs:
    ports:
      - "8221:80"
    deploy:
      resources:
        limits:
          memory: 256M
      placement:
        constraints:
          - node.labels.dc == hetzner
  storybook:
    ports:
      - "8222:80"
    deploy:
      resources:
        limits:
          memory: 256M
      placement:
        constraints:
          - node.labels.dc == hetzner