version: "3.6"

services:
  frontend:
    deploy:
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
          - node.labels.dc == hetzner
  docs:
    deploy:
      resources:
        limits:
          memory: 256M
      placement:
        constraints:
          - node.labels.dc == hetzner
  storybook:
    deploy:
      resources:
        limits:
          memory: 256M
      placement:
        constraints:
          - node.labels.dc == hetzner