version: "3.6"

services:
  frontend:
    ports:
      - 8080
    deploy:
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
          - node.labels.dc == hetzner
  docs:
    ports:
      - 80
    deploy:
      resources:
        limits:
          memory: 256M
      placement:
        constraints:
          - node.labels.dc == hetzner
  storybook:
    ports:
      - 80
    deploy:
      resources:
        limits:
          memory: 256M
      placement:
        constraints:
          - node.labels.dc == hetzner