version: "3.6"

services:
  frontend:
    image: "${DOCKER_REGISTRY}/n2o/demo"
    deploy:
      resources:
        limits:
          memory: 700M
      placement:
        constraints:
          - node.labels.dc == hetzner
  docs:
    image: "${DOCKER_REGISTRY}/n2o/docs"
    deploy:
      resources:
        limits:
          memory: 256M
      placement:
        constraints:
          - node.labels.dc == hetzner
  storybook:
    image: "${DOCKER_REGISTRY}/n2o/storybook"
    deploy:
      resources:
        limits:
          memory: 256M
      placement:
        constraints:
          - node.labels.dc == hetzner