version: "3.6"

services:
  frontend:
    image: "${DOCKER_REGISTRY}/n2o/demo:${TAG}"
    ports:
      - "8080"
    deploy:
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
          - node.role == worker
  docusaurus:
    image: "${DOCKER_REGISTRY}/n2o/docusaurus:${TAG}"
    ports:
      - "80"
    deploy:
      resources:
        limits:
          memory: 256M
      placement:
        constraints:
          - node.role == worker
  sandbox:
    image: "${DOCKER_REGISTRY}/n2o/sandbox:${TAG}"
    ports:
      - "8080"
    deploy:
      resources:
        limits:
          memory: 512M
      placement:
        constraints:
          - node.role == worker
