version: "3.6"

services:
  frontend:
    image: "${DOCKER_REGISTRY}/n2o/demo:${TAG}"
    ports:
      - "8080"
    deploy:
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
          - node.labels.dc == hetzner
  docs:
    image: "${DOCKER_REGISTRY}/n2o/docs:${TAG}"
    ports:
      - "80"
    deploy:
      resources:
        limits:
          memory: 256M
      placement:
        constraints:
          - node.labels.dc == hetzner
  storybook:
    image: "${DOCKER_REGISTRY}/n2o/storybook:${TAG}"
    ports:
      - "80"
    deploy:
      resources:
        limits:
          memory: 256M
      placement:
        constraints:
          - node.labels.dc == hetzner